### ISSUE TITLE
Cannot split spans before punctuation (with space or lb)

### ISSUE THREAD

**Issue by dhowe** [dhowe/annograms#3]
![image](https://user-images.githubusercontent.com/737638/146676535-06a267b5-416a-4e37-a8fc-d8b079e52f6e.png)

**Comment by dhowe** [comment]
<img width="848" alt="image" src="https://user-images.githubusercontent.com/737638/146928723-fff72153-53eb-42eb-97fd-8eeba12652df.png">

**Comment by Real-John-Cheung** [comment]
should be fixed with this https://observablehq.com/compare/8b3a2ddcb3bc611b...c61c94dc0b89fb4b

**Comment by dhowe** [comment]
this should be a fix for the punct part, have to double-check line breaks...

**Comment by dhowe** [comment]
@Real-John-Cheung I am still seeing this problem:

<img width="872" alt="image" src="https://user-images.githubusercontent.com/737638/148379390-a2a4a47d-e320-4dd1-a22c-4845fd7de3a9.png">
