### ISSUE TITLE
Simple webpage for generation

### ISSUE THREAD

**Issue by dhowe** [dhowe/annograms#39]
- [x] Create a simple webpage showing paragraph view (with annotations shown on hover, using same CSS)
- [x] Add regenerate button
- [x] Implement with web-worker
- [x] Hookup toggle for annotations (should hide annotations/underlines when unchecked) [JC]
- [x] Add same toggle to observable page [JC] 

![image](https://user-images.githubusercontent.com/737638/154897534-7572aa0e-7f8c-43a3-b6b8-50a8d0f29a16.png)

![image](https://user-images.githubusercontent.com/737638/154897978-c98540c4-6914-438d-81a7-2d5e29f82005.png)

**Comment by Real-John-Cheung** [comment]
cursor and underline should be fixed in #41

**Comment by dhowe** [comment]
thanks, looks good.

Not sure if anything can be done about this, but the intention of disabling annotations is to be able to easily copy/paste parts of the generated output, however I still see this strange behavior where it (chrome) attempts to drag and drop the fragment:

<img width="2560" alt="Screenshot 2022-02-21 at 10 17 56 PM" src="https://user-images.githubusercontent.com/737638/154972719-38d1e40a-ae4d-4b9b-a457-ae53e92425c4.png">

**Comment by Real-John-Cheung** [comment]
> this strange behavior where it (chrome) attempts to drag and drop the fragment:

should be fix in #42
